export default class Size {
  static WELCOME_BUTTON_HEIGHT = 40;
  static WELCOME_BUTTON_CONTAINER_SOCIAL_HEIGHT = 30;
  static WELCOME_TABBAR_HEIGHT = 50;

  static WELCOME_WIDTH_SPACE = 10;
  static WELCOME_HEIGHT_SPACE = 10;

  static MAX_LENGTH_DESCRIPTION = 300;
  static MAX_LENGTH_TITLE = 25;
}
